# Generated by Django 2.2.1 on 2019-07-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190724_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='content/media/Site-Data/Images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/media/Site-Data/Images/'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='bg_img',
            field=models.ImageField(blank=True, null=True, upload_to='content/media/Images/Interests/'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='URL to the Interests Page'),
        ),
    ]
