# Generated by Django 2.2.3 on 2019-08-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_contact'),
        ('home', '0012_auto_20190727_0514'),
    ]

    operations = [
    ]
