# Generated by Django 2.2.3 on 2019-08-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_merge_20190809_0801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
